spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gradleappdb
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    org:
      seasar:
        doma: DEBUG